# Julia Diline Başlangıç
**Julia** dili, 
- Python gibi gözüken, 
- LISP gibi hissetiren, 
- C ve FORTRAN kadar hızlı olan 
bir teknik hesaplamalar için kullanılan bir dildir.

# REPL (Read, Evaluate, Print, Loop)
Julia'nın interaktif konsoluna REPL (Oku, Hesapla, Sonucu Yaz, Tekrarla) adı verilmiştir.  
Konsolun 4 parçası bulunur:
- **julia>**:Julia konutlarının çalıştırıldığı istemci
- **shell>**:Eğer UNIX tarzı bir işletim sistemi kullanıyorsanız BASH komutlarını bu istemci üzerinden çalıştırabilirsiniz. shell konsoluna **';'** yazarak geçiş yapabilirsiniz.
- **help?>**:Bu konsola **'?'** yazarak geçiş yapabilirsiniz. Bir fonksiyon ya da kütüphane hakkında bilgi almak için kullanılır.
- **pkg>**: Kütüphane yükleme, build etme vb. işlemler için kullanılan paket yöneticisidir.  Aynı zamanda **julia>** konsolu üzerinden **Pkg.komut_adi()** olarak ya da **']'** işareti kullanılarak erişilebilir. Bu komutlardan bazıları; add, rm, status, update komutlarıdır.
- Yüklü kütüphaneleri konsol ortamına ilave etmek için C-tarzı diller gibi **'using'** ya da Python gibi **'import'** ibaresini kullanır.
- Özet olarak kullanılacak simgeler ve kısayollar:
 - **?**
 - **;**
 - **]**
 - Yukarıda bahsedilmeyen **ans**, son işlemden kalan cevabı içinde tutar

## **Örnekler:**  
**julia>** a=5  
**julia>** dizi1B = [5,3]  
**julia>** dizi2B = [5 3]  
**shell>** ls # o anki bulunan klasörü listeler  
**shell>** mkdir klasor #"klasor" adında klasor oluşturur
**help?>** log() # Logaritma fonksiyonu hakkında bilgi verir  
**pkg>** add IJulia # IJulia kütüphanesini yükler  
**pkg>** rm kutuphane_adi # Kütüphaneyi kaldırır

İsterseniz birkaç matematiksel işlem ile başlayalım. Aritmetik işlemler herkesin bildiği üzere 5+5, 5-4, 5\*3, 5^3 (Python gibi "\**" değil), a+=5, a*=5 vb işlemler ile sağlanabilir. Bunun dışında operator(arguman1, arguman2,...) şeklinde de bir kullanım mevcuttur.

In [10]:
+(5,4,6) # 15

15

In [9]:
*(1,2,3) # 6

6

Diğer dillerden farklı olarak kesirleri *ondalıklı* veya *float* tipi ile göstermek dışında **//** ibaresi ile oluşturabilirsiniz.

In [14]:
a=2//3; # 2/3
b=2/3 # 0.66
a,b

(2//3, 0.6666666666666666)

Ayrıca REPL komut istemi **Unicode** karakterleri ve **LaTeX** (matematiksel semboller) notasyonunu da destekler.  
Böylelikle matematiksel ifadelerin kod içinde kullanımıda sağlanmış olur. (Yine de best practice olarak alfanumerik karakterlerin kullanımı daha yaygın olacağı kesin **:)** ).  
Aynı zamanda okunulabilirlik için değişkenlerin sayılar ile çarpımları * (çarpı) işareti kullanılmadan da kullanılabilir.

In [19]:
print("α+β=180°") # \alpha <TAB> + \beta <TAB> = 180 \degree <TAB>

α+β=180°

In [20]:
x=2;
2x+4 # 8

8

Dizilerde elementer (element bazlı) işlemler için dağıtıcı (broadcast) operatörü olan **"."** nın kullanımı da şöyledir:
- dizi1.*operator*(dizi2) = dizi1'in dizi2'deki karşılığını al ve operatör işlemini uygula.

In [24]:
a=[1,2,3]; b=[2,3,4];
a.+(b)

3-element Array{Int64,1}:
 3
 5
 7

## Stringler ve Karakterler
Stringler ve karakterler arasındaki farklar tırnak işaretleri ile belirlenir.
- "Kelime"
- """Winston birden duraksadı. "Ben bu günlüğü kim için yazıyorum?" dedi."""
- 'J','u','l','i','a' 

Stringlerin birleşimi 
- *string("Julia"," Winston"," Telescreen")* # "Julia Winston Telescreen"
- replace(degistirilecek_str,aranan ==> yerine_gecen), findfirst(chr,str)
- length(str)

In [87]:
cumle="Julia ogreniyorum"
uzunluk,python_julia,ilk_y_harfi=length(cumle),
                                replace(cumle,"Julia" =>"Python"),
                                findfirst("og",cumle)

(17, "Python ogreniyorum", 7:8)

## Değişkenler ve çoklu atama
Değişken isimleri **noktalama işaretleri ve sayılar hariç** her karakter ile başlaması uygundur.  
Hatta özel *Unicode* karakterleri de bunlar için kullanılabilir.  
Print fonksiyonunda değişkenlere erişilmesi için *$* işareti kullanılır.

In [3]:
🐱=5; 🐢=5e3; 🐶=9.0; # ya da 
🐱,🐢,🐶=(5,5e3,9.0);
_underscore="_";
🐱,🐢,🐶,_underscore # Buradaki çıktıya dikkat ederseniz () işaretleri arasındadır. Bu çıktının tuple (sıralı dizi) olduğunu gösterir.

(5, 5000.0, 9.0, "_")

In [29]:
print("Winston'ın $🐱 tane kedisi var")

Winston'ın 5 tane kedisi var

In [32]:
x,y=3,4;
println("Julia'nın $x x $y boyutlu $(x*y) verisi var")

Julia'nın 3 x 4 boyutlu 12 verisi var


# Fonksiyonlar
## Fonksiyon tanımlama
- function fonk_ad(arg1,arg2=varsayılan_deger,....) | function fonk_ad(args...)
    - yapılacak seyler
    - println("Ben bir fonksiyonum")
        - function fonk_ici_fonk(args)
           - kapsayan fonksiyona yardımcı
           - olan şeyler yap
        - end
- end 
*veya*
- fonk_ad(args)= islemler
*veya*
Lambda (anonim) fonksiyonlar
- fonk_ad = (arg1,arg2,..) -> islemler
fonk_ad!(args) : fonksiyonun verilen argüman içeriğini değiştirir

## Explicit Tipli Fonksiyonlar
- function fonk_ad(args::*T*)::Tip *where T <:* Tip
    - bir seyler yap
    - sonuc=islem_sonucu
    - return sonuc
- end

In [21]:
function merhaba_de(ad,soyad)
    println("Merhaba $ad $soyad" * ", tanıştığımıza memnun oldum.")
end

#samimiyet önemli
merhaba2(ad)=println("Merhaba $ad")
nasılsın= (ad,soyad="The Director") -> println("Nasıl gidiyor, $ad $soyad ?")

merhaba_de("Andrei","Tartovsky")
merhaba2("Andrei")
nasılsın("Andrei")

Merhaba Andrei Tartovsky, tanıştığımıza memnun oldum.
Merhaba Andrei
Nasıl gidiyor, Andrei The Director ?


In [108]:
#sayısal fonksiyonlar deneyelim
A=rand(1:6,4,4); B=collect(rand(1:100,6));
kare_Al(x) = x^2
topla_Bakalim(dizi)=sum(dizi)
kare_Al(A)
topla_Bakalim(A)

59

In [109]:
#kare_Al(B) : hata verir vektörlerin karesi alınamaz
kare_Al.(B) #kare_Al fonksiyonun işlevini her bir element için uyguladı (yayma:broadcasting)

6-element Array{Int64,1}:
 4225
    4
 6889
 7396
 3364
 4900

In [112]:
sort(B),B

([2, 58, 65, 70, 83, 86], [2, 58, 65, 70, 83, 86])

In [111]:
sort!(B),B

([2, 58, 65, 70, 83, 86], [2, 58, 65, 70, 83, 86])

In [115]:
function sayiDonustur(sayi::T)::String where T <:Number
    return "$sayi"
end
sayiDonustur(6)
#sayiDonustur("gd") -> hata

"6"

## Diziler,Matrisler ve Kullanılabilecek Diğer Fonksiyonlar
Dizi ve matrisler alışkın olduğumuz **[]** köşeli parantez yapısı ile belirtilmiş.  
Dizi tanımı ise **Array{Tip,(boyut))** şeklinde: burada tip **Any**, **String**, **Char**, **Int64**, **Float64** vb. tipleri temsil ederken boyut 1 ile n'e kadar olan tuple listesi ile temsil edilir.  
Dizi tanımlarken açık olarak tipte belirtebiliriz:
- Tip[tip_eleman1,tip_eleman2]
- Tip[] #boş tip dizisi
Örneğin:  
- dizi1D=[1,2,3]
    - Array{Int64,1} türünde bir dizi döndürür.
- matris2D=[1.0 2 3; **reshape(rand(3)*10,(1,3))**]
    - Array{Float64,2} türünde 1x3 matris döndürür. Dizi oluşturulurken arada boşluk bırakılması sütunları temsil eder. 
    - Sütunlardan sonra ; işareti ile alt satıra geçilir.
    - **rand(boyut,boyut,..) ya da rand(sayi)*** : *sayi* kadar ya da *boyut x boyut x boyut x ..* boyutlarında  [0,1] aralığında değerler döndürür.
        - Kardeşi diyebileceğimiz **randn(boyut,boyut,...) ya da randn(sayi)** ise normal dağılımlı (ortalaması=0, standart sapması=1 olan değerler döndürür.
    - **reshape(array,(boyut1,boyut2,..))** verilen diziyi boyut şeklinde sütun ve satır yapısına dönüştürür.  
        - Buradaki (1,3); 1,3 şeklinde de yazılabilirdi.
- dizi_dizisi=[[1,2,3,4],collect(4:7)]
    - Array{Array{Int64,1},1} - Dizi tipli bir dizi  
    - **collect()** range objelerini array olarak döndürür
        - Bunun diğer bir yöntemi de [baslangic:(adim:)son...] olarak yazılmasıdır.
    - **Range (aralık)** objeleri *baslangic:adım:son* olarak belirlenebilir.
        - Bu objeler **for** yapılarında ya da dizi oluşturmada kolaylık sağlar
        - Son geri dönen sıralı diziye dahildir.
- dizi_comprehension = [ i+j for i in 1:5, j in 1:10]
    - Lambda fonksiyonlarına benzer bir dille yazılan bu ifadelere comprehension deniyor.
        - [ işlem for birinci_par in (range|iterable), ikinci_par in (range|iterable),...]

- size(matris) : matris boyutu

In [37]:
#=
for rakam in 1:10 
    print(rakam)
end
=#

# for rakam in 1:10 print(rakam) end
#sizce rakamlar ne ile dolu? 
#ipucu: ";" işaretini kaldırın veya typeof(rakamlar)
rakamlar=[println(rakam) for rakam in 1:10];
#typeof(rakamlar)

1
2
3
4
5
6
7
8
9
10


Array{Nothing,1}

In [90]:
dizi1D=[1,2,3];
matris2D=[1.0 2 3; reshape(rand(3)*10,1,3)];
dizi_dizisi=[[1,2,3,4],collect(4:7)]; 
dizi_comprehension = [ i+j for i in 1:5, j in 1:10]
string_dizi=["bu","bir","string","dizisidir"];
intdizi=Int64[1,2,4];
dizi1D

Array{Int64,1}

In [57]:
matris2D

2×3 Array{Float64,2}:
 1.0      2.0      3.0
 5.89789  6.09755  9.00343

In [19]:
dizi_dizisi

2-element Array{Array{Int64,1},1}:
 [1, 2, 3, 4]
 [4, 5, 6, 7]

In [18]:
dizi_comprehension

5×10 Array{Int64,2}:
 2  3  4  5   6   7   8   9  10  11
 3  4  5  6   7   8   9  10  11  12
 4  5  6  7   8   9  10  11  12  13
 5  6  7  8   9  10  11  12  13  14
 6  7  8  9  10  11  12  13  14  15

In [22]:
string_dizi

4-element Array{String,1}:
 "bu"
 "bir"
 "string"
 "dizisidir"

In [35]:
intdizi

3-element Array{Int64,1}:
 1
 2
 4

### Dizi verilerine ulaşma, veri ekleme ve çıkarma
Python tarzı bir index yöntemi var.  
a=Float64[1.0 2.0 3.0]
- a[[2,3]] # 2.0 3.0
- pop!(dizi) : son elementi çıkar
- popfirst!(dizi) : ilk elementi çıkar
- push!()
- pushfirst()
- append!(dizi1,dizi2)
- deleteat!(dizi,silinecek_element_idx)
- sort!()
- deger in dizi : *deger* dizide var mı yok mu
- join(dizi, ayrac) : dizi degerlerini arasına ayrac koyarak cıkar 

Dikkat edilirse Julia'nın index değeri 1 ile başladığı görülür.

In [130]:
 for i in (dizi_dizisi[1][1],intdizi[3],matris2D[2,3])
    println(i)
end

1
4
2.7740931007094094


In [ ]:
Tipik dizi türleri içinde fonksiyonlar vardır:
- zeros(boyut1,boyut2,...)
- ones(boyut1,boyut2,...)
- trues(boyut1,boyut2,...) , falses(boyut1,boyut2,...)
Dizileri doldurmak içinde *fill(doldurulacak_item,(boyutlar))* fonksiyonu kullanılır.
Ya da *repeat(dizi,(boyutlar))* şeklinde diziyi boyutlar içerisinde yayabiliriz

In [51]:
birler=fill(1,2,2)
ikiyle_degistir=fill!(birler,2) 
# Ünlem işareti özel bir operatördür. 
# Bir fonksiyonun sonunda ! var ise bu önceden belirlenmiş bir değişkenin fonksiyondan dönen değerler ile değişeceğini işaret eder.
# ikiler=repeat(birler*2,2,2)
birler

2×2 Array{Int64,2}:
 2  2
 2  2

In [91]:
matris2D[:,2] #ikinci sütunu al

2-element Array{Float64,1}:
 2.0
 6.097552280307632

In [90]:
matris2D[1,:] #birinci satırı al

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

Güzel bir örnek olarak şu verilebilir.

In [52]:
A=rand(1:10,(5,5)) #random 5x5 matris oluştur

5×5 Array{Int64,2}:
 8  2  2  10   8
 5  4  6   4  10
 4  5  5   2   2
 6  6  3  10   4
 5  9  5   8   5

In [53]:
A.==5 #A matrisinde değerleri 5 olanları bul ve true false matrisi döndür

5×5 BitArray{2}:
 0  0  0  0  0
 1  0  0  0  0
 0  1  1  0  0
 0  0  0  0  0
 1  0  1  0  1

In [54]:
A[A.==5].=6; #true false ile seçili olan indisleri 6 yap
A

5×5 Array{Int64,2}:
 8  2  2  10   8
 6  4  6   4  10
 4  6  6   2   2
 6  6  3  10   4
 6  9  6   8   6

Matris ve vektör işlemleride yine $+,*,-, '$ (Transpose) vb. operatörleri ile yapılabilmektedir. Boyutların işlem için geçerli olmasına dikkat edin yeter.

In [68]:
A,B= [2 2; 3 3], [1 1; 3 3];
matrisCarpım,elementselCarpım= A*B, A.*B

([8 8; 12 12], [2 2; 9 9])

Vektör ve matrisleri birleştirmek için **hcat(matris veya vektör,matris veya vektör) ve vcat(matris veya vektör,matris veya vektör)** fonksiyonları kullanılır. 
- [A;B] = vcat(A,B) # v dikey (vertical)
- [A B] = hcat(A,B) # h yatay (horizontal)
- [A B; C D;] = hvcat()
Eğer bir matrisi vektöre dönüştürmek isterseniz **vec(matris)** kullanılabilir.