## Diziler,Matrisler ve Kullanılabilecek Diğer Fonksiyonlar
Dizi ve matrisler alışkın olduğumuz **[]** köşeli parantez yapısı ile belirtilmiş.  
Dizi tanımı ise **Array{Tip,(boyut))** şeklinde: burada tip **Any**, **String**, **Char**, **Int64**, **Float64** vb. tipleri temsil ederken boyut 1 ile n'e kadar olan tuple listesi ile temsil edilir.  
Dizi tanımlarken açık olarak tipte belirtebiliriz:
- Tip[tip_eleman1,tip_eleman2]
- Tip[] #boş tip dizisi
Örneğin:  
- dizi1D=[1,2,3]
    - Array{Int64,1} türünde bir dizi döndürür.
- matris2D=[1.0 2 3; **reshape(rand(3)*10,(1,3))**]
    - Array{Float64,2} türünde 1x3 matris döndürür. Dizi oluşturulurken arada boşluk bırakılması sütunları temsil eder. 
    - Sütunlardan sonra ; işareti ile alt satıra geçilir.
    - **rand(boyut,boyut,..) ya da rand(sayi)*** : *sayi* kadar ya da *boyut x boyut x boyut x ..* boyutlarında  [0,1] aralığında değerler döndürür.
        - Kardeşi diyebileceğimiz **randn(boyut,boyut,...) ya da randn(sayi)** ise normal dağılımlı (ortalaması=0, standart sapması=1 olan değerler döndürür.
    - **reshape(array,(boyut1,boyut2,..))** verilen diziyi boyut şeklinde sütun ve satır yapısına dönüştürür.  
        - Buradaki (1,3); 1,3 şeklinde de yazılabilirdi.
- dizi_dizisi=[[1,2,3,4],collect(4:7)]
    - Array{Array{Int64,1},1} - Dizi tipli bir dizi  
    - **collect()** range objelerini array olarak döndürür
        - Bunun diğer bir yöntemi de [baslangic:(adim:)son...] olarak yazılmasıdır.
    - **Range (aralık)** objeleri *baslangic:adım:son* olarak belirlenebilir.
        - Bu objeler **for** yapılarında ya da dizi oluşturmada kolaylık sağlar
        - Son geri dönen sıralı diziye dahildir.
- dizi_comprehension = [ i+j for i in 1:5, j in 1:10]
    - Lambda fonksiyonlarına benzer bir dille yazılan bu ifadelere comprehension deniyor.
        - [ işlem for birinci_par in (range|iterable), ikinci_par in (range|iterable),...]

- size(matris) : matris boyutu

In [37]:
#=
for rakam in 1:10 
    print(rakam)
end
=#

# for rakam in 1:10 print(rakam) end
#sizce rakamlar ne ile dolu? 
#ipucu: ";" işaretini kaldırın veya typeof(rakamlar)
rakamlar=[println(rakam) for rakam in 1:10];
#typeof(rakamlar)

1
2
3
4
5
6
7
8
9
10


Array{Nothing,1}

In [90]:
dizi1D=[1,2,3];
matris2D=[1.0 2 3; reshape(rand(3)*10,1,3)];
dizi_dizisi=[[1,2,3,4],collect(4:7)]; 
dizi_comprehension = [ i+j for i in 1:5, j in 1:10]
string_dizi=["bu","bir","string","dizisidir"];
intdizi=Int64[1,2,4];
dizi1D

Array{Int64,1}

In [57]:
matris2D

2×3 Array{Float64,2}:
 1.0      2.0      3.0
 5.89789  6.09755  9.00343

In [19]:
dizi_dizisi

2-element Array{Array{Int64,1},1}:
 [1, 2, 3, 4]
 [4, 5, 6, 7]

In [18]:
dizi_comprehension

5×10 Array{Int64,2}:
 2  3  4  5   6   7   8   9  10  11
 3  4  5  6   7   8   9  10  11  12
 4  5  6  7   8   9  10  11  12  13
 5  6  7  8   9  10  11  12  13  14
 6  7  8  9  10  11  12  13  14  15

In [22]:
string_dizi

4-element Array{String,1}:
 "bu"
 "bir"
 "string"
 "dizisidir"

In [35]:
intdizi

3-element Array{Int64,1}:
 1
 2
 4

### Dizi verilerine ulaşma, veri ekleme ve çıkarma
Python tarzı bir index yöntemi var.  
a=Float64[1.0 2.0 3.0]
- a[[2,3]] # 2.0 3.0
- pop!(dizi) : son elementi çıkar
- popfirst!(dizi) : ilk elementi çıkar
- push!()
- pushfirst()
- append!(dizi1,dizi2)
- deleteat!(dizi,silinecek_element_idx)
- sort!()
- deger in dizi : *deger* dizide var mı yok mu
- join(dizi, ayrac) : dizi degerlerini arasına ayrac koyarak cıkar 

Dikkat edilirse Julia'nın index değeri 1 ile başladığı görülür.

In [130]:
 for i in (dizi_dizisi[1][1],intdizi[3],matris2D[2,3])
    println(i)
end

1
4
2.7740931007094094


In [ ]:
Tipik dizi türleri içinde fonksiyonlar vardır:
- zeros(boyut1,boyut2,...)
- ones(boyut1,boyut2,...)
- trues(boyut1,boyut2,...) , falses(boyut1,boyut2,...)
Dizileri doldurmak içinde *fill(doldurulacak_item,(boyutlar))* fonksiyonu kullanılır.
Ya da *repeat(dizi,(boyutlar))* şeklinde diziyi boyutlar içerisinde yayabiliriz

In [51]:
birler=fill(1,2,2)
ikiyle_degistir=fill!(birler,2) 
# Ünlem işareti özel bir operatördür. 
# Bir fonksiyonun sonunda ! var ise bu önceden belirlenmiş bir değişkenin fonksiyondan dönen değerler ile değişeceğini işaret eder.
# ikiler=repeat(birler*2,2,2)
birler

2×2 Array{Int64,2}:
 2  2
 2  2

In [91]:
matris2D[:,2] #ikinci sütunu al

2-element Array{Float64,1}:
 2.0
 6.097552280307632

In [90]:
matris2D[1,:] #birinci satırı al

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

Güzel bir örnek olarak şu verilebilir.

In [52]:
A=rand(1:10,(5,5)) #random 5x5 matris oluştur

5×5 Array{Int64,2}:
 8  2  2  10   8
 5  4  6   4  10
 4  5  5   2   2
 6  6  3  10   4
 5  9  5   8   5

In [53]:
A.==5 #A matrisinde değerleri 5 olanları bul ve true false matrisi döndür

5×5 BitArray{2}:
 0  0  0  0  0
 1  0  0  0  0
 0  1  1  0  0
 0  0  0  0  0
 1  0  1  0  1

In [54]:
A[A.==5].=6; #true false ile seçili olan indisleri 6 yap
A

5×5 Array{Int64,2}:
 8  2  2  10   8
 6  4  6   4  10
 4  6  6   2   2
 6  6  3  10   4
 6  9  6   8   6

Matris ve vektör işlemleride yine $+,*,-, '$ (Transpose) vb. operatörleri ile yapılabilmektedir. Boyutların işlem için geçerli olmasına dikkat edin yeter.

In [68]:
A,B= [2 2; 3 3], [1 1; 3 3];
matrisCarpım,elementselCarpım= A*B, A.*B

([8 8; 12 12], [2 2; 9 9])

Vektör ve matrisleri birleştirmek için **hcat(matris veya vektör,matris veya vektör) ve vcat(matris veya vektör,matris veya vektör)** fonksiyonları kullanılır. 
- [A;B] = vcat(A,B) # v dikey (vertical)
- [A B] = hcat(A,B) # h yatay (horizontal)
- [A B; C D;] = hvcat()
Eğer bir matrisi vektöre dönüştürmek isterseniz **vec(matris)** kullanılabilir.